name: syncfusion_officecore
description: Syncfusion Flutter Office Core is a dependant library for Syncfusion Flutter XlsIO, written natively in Dart for creating Excel from scratch.
version: 32.1.19
homepage: https://github.com/syncfusion/flutter-widgets/tree/master/packages/syncfusion_officecore

environment:
  sdk: ^3.7.0
  flutter: '>=3.29.0'

dependencies:
  flutter:
    sdk: flutter
  syncfusion_flutter_core:
    path: ../syncfusion_flutter_core
