
name: syncfusion_localizations
description: Syncfusion Localizations package contains localized text for 77 cultures for all the applicable Syncfusion Flutter Widgets. 
version: 32.1.19
homepage: https://github.com/syncfusion/flutter-widgets/tree/master/packages/syncfusion_localizations

environment:
  sdk: ^3.7.0
  flutter: ">=3.35.1"

dependencies:
  flutter:
    sdk: flutter
  intl: '>=0.18.1 <0.21.0'
  syncfusion_flutter_core:
    path: ../syncfusion_flutter_core
