name: datagrid_export_example
description: This project demonstrates how to use Syncfusion Flutter DataGrid Export widget.
publish_to: "none"
version: 1.0.0+1

environment:
  sdk: ^3.7.0

flutter:
  uses-material-design: true

dependencies:
  flutter:
    sdk: flutter
  web: ^1.1.0
  open_file: ^3.2.1
  path_provider: ^2.0.2
  syncfusion_flutter_datagrid_export:
    path: ../

dev_dependencies:
  flutter_test:
    sdk: flutter
