name: syncfusion_pdfviewer_android
description: An optional Android platform implementation of the Flutter PDF Viewer library that lets you view PDF documents seamlessly and efficiently, which uses PDFium for rendering.
version: 30.1.37
homepage: https://github.com/syncfusion/flutter-widgets/tree/master/packages/syncfusion_pdfviewer_android

environment:
  sdk: ^3.7.0
  flutter: '>=3.35.1'

flutter:
  plugin:
    platforms:
      android:
        package: com.syncfusion.flutter.pdfviewer.android
        pluginClass: SyncfusionFlutterPdfViewerPdfiumPlugin

dependencies:
  flutter:
    sdk: flutter
  plugin_platform_interface: ^2.0.2

dev_dependencies:
  flutter_test:
    sdk: flutter
