name: syncfusion_flutter_gauges
description: The Flutter gauges library includes a linear gauge and radial gauge (a.k.a. circular gauge) to create modern, interactive, animated gauges and radial sliders.
version: 32.1.19
homepage: https://github.com/syncfusion/flutter-widgets/tree/master/packages/syncfusion_flutter_gauges

environment:
  sdk: ^3.7.0
  flutter: ">=3.35.1"

flutter:
  uses-material-design: true

dependencies:
  flutter:
    sdk: flutter
  intl: '>=0.18.1 <0.21.0'
  syncfusion_flutter_core:
    path: ../syncfusion_flutter_core
