name: syncfusion_flutter_maps
description: A Flutter Maps library for creating beautiful, interactive, and customizable maps from shape files or WMTS services to visualize the geographical area.
version: 32.1.19
homepage: https://github.com/syncfusion/flutter-widgets/tree/master/packages/syncfusion_flutter_maps

screenshots:
  - description: 'This screenshot shows the different types of shape layer feature.'
    path: screenshots/shape_layer_maps.png
  - description: 'This screenshot shows the different types of tile layer feature.'
    path: screenshots/tile_layer_maps.png

environment:
  sdk: ^3.7.0
  flutter: ">=3.35.1"

dependencies:
  flutter:
    sdk: flutter
  http: ^1.0.0
  vector_math: ">=2.2.0 <=3.0.0"
  syncfusion_flutter_core:
    path: ../syncfusion_flutter_core
