name: syncfusion_flutter_core
description: Syncfusion Flutter Core is a dependent package for all the Syncfusion Flutter widgets. 
version: 32.1.19
homepage: https://github.com/syncfusion/flutter-widgets/tree/master/packages/syncfusion_flutter_core

environment:
  sdk: ^3.7.0
  flutter: ">=3.35.1"

dependencies:
  flutter:
    sdk: flutter
  vector_math: ">=2.2.0 <=4.0.0"

