name: syncfusion_flutter_signaturepad
description: The Flutter Signature Pad widget allows you to capture smooth and more realistic signatures through drawn gestures and save it as an image.
version: 32.1.19
homepage: https://github.com/syncfusion/flutter-widgets/tree/master/packages/syncfusion_flutter_signaturepad

screenshots:
  - description: 'This demo shows signature drawn on signature pad.'
    path: screenshots/signature_pad.gif

environment:
  sdk: ^3.7.0
  flutter: ">=3.35.1"

dependencies:
  flutter:
    sdk: flutter
  web: ^1.0.0
  syncfusion_flutter_core:
    path: ../syncfusion_flutter_core
