name: syncfusion_flutter_datagrid_export
description: The Syncfusion Flutter DataGrid Export library is used to export the DataGrid content to Excel and Pdf format with several customization options.
version: 32.1.19
homepage: https://github.com/syncfusion/flutter-widgets/tree/master/packages/syncfusion_flutter_datagrid_export

environment:
  sdk: ^3.7.0
  flutter: ">=3.35.1"

dependencies:
  flutter:
    sdk: flutter
  collection: ">=1.9.0 <=2.0.0"
  syncfusion_flutter_datagrid:
    path: ../syncfusion_flutter_datagrid

  syncfusion_flutter_xlsio:
    path: ../syncfusion_flutter_xlsio

  syncfusion_officecore:
    path: ../syncfusion_officecore

  syncfusion_flutter_pdf:
    path: ../syncfusion_flutter_pdf
